version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/posgres
    ports:
      - 5432:5432
  app:
    build: .
    container_name: rentx
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
    ports:
      - 3333:3333

volumes:
  pgdata:
    driver: local